config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  resources :collection_notes
  resources :collections
  get 'logout' => 'session#destroy', :as => 'logout'
  get 'login' => 'session#new', :as => 'login'
  post 'login' => 'session#create'
  delete 'users/:user_id/notes/:id', to: 'notes#destroy', as: 'destroy_user_note'
  resources :users do
    resources :notes do
      get 'share' => 'notes#share', :as => 'share'
      post 'share_with_friend' => 'notes#share_with_friend'
      delete 'unshare_with_friend' => 'notes#unshare_with_friend'
    end
    resources :collections do
      post 'add_note' => 'collections#add_note'
      delete 'delete_note' => 'collections#delete_note'
    end
    resources :friendships, only: [:index, :create, :update, :destroy]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
  root "users#login"
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_many :collections_notes
  validates :name, presence: true, length: { maximum: 10 }, uniqueness: { case_sensitive: false }

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  # before_action :set_collection, only: %i[ show edit update destroy ]

  # GET /collections
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  def create
    @user = User.find(params[:user_id])
    if params[:notes]
      @collection = @user.collections.create(:name => params[:name], :notes => params[:notes])
    else
      @collection = @user.collections.create(:name => params[:name])
    end

    if @collection.save
      flash[:notice] = "Collection created!"
      redirect_to user_collections_url(@user.id)
    else
      flash[:alert] = "Collection not saved!"
      redirect_to user_collections_url(@user.id)
    end
  end

  # DELETE /collections/1
  def destroy
    puts "-------------------------------DELETE COLLECTION----------------"
    if logged?
      collection = Collection.find(params['id'])
      user = User.find(collection.user_id)
      CollectionNote.where(collection_id: collection.id).destroy_all
      collection.destroy

      redirect_to user_collections_url(user), notice: "Collection was successfully destroyed."
    end
  end

  def add_note
    puts "-------------------------------ADD NOTE TO COLLECTION----------------"
    if logged?
      CollectionNote.create(:collection_id => params['collection_id'], :note_id => params['note_id'])
      
      redirect_to edit_user_note_path(params['user_id'], params['note_id'])
    end
  end

  def delete_note
    puts "-------------------------------DELETE NOTE TO COLLECTION----------------"
    if logged?
      CollectionNote.where(:collection_id => params['collection_id'], :note_id => params['note_id']).destroy_all

      redirect_to edit_user_note_path(params[:user_id], params[:note_id])
    end
  end


  private

    # Only allow a list of trusted parameters through.
    def collection_params
      params.require(:collection).permit(:name, :user_id)
    end

    def logged?
      session[:username]
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
    def find_collections(user_id)
        collections = []
        collections = Collection.where(user_id: user_id.to_i)
    end

    def belong_to_collection(collection_id,note_id)
        CollectionNote.where(collection_id: collection_id, note_id: note_id)
    end

    def find_collection_notes(collection_id)
        CollectionNote.where(collection_id: collection_id)
    end
end

app/views/collections/index.html.erb
<% user = get_user_name(params[:user_id]) %>
<h2>Collections of <span class="title-h2"><%=user.username%></span></h2>

<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>
<%= form_with(model: @collection, url: user_collections_path, method: :post) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.submit "Crear colección", class: "button-primary" %>
<% end %>
<div id="collection">
  <% @collections.each do |collection| %>
    <div class="user-card">
      <div class="user-info">
      <h2>
        <i class="fa fa-book fa-xl"></i>
      </h2>
      <h2 style="padding-left: 20px">
        <%= collection.name %>
      </h2>
      
      </div>
      <div class="user-bottons">
        <%= button_to '<i class="fa-solid fa-eye"></i>'.html_safe, user_collection_path({user_id: params[:user_id],id: collection.id}), method: :get, class: "button-primary" %>
        <%= button_to '<i class="fa fa-trash"></i>'.html_safe, user_collection_path(params[:user_id], collection.id), method: :delete, class: "button-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/collections/show.html.erb
<% user = User.find(params[:user_id]) %>
<% collection = Collection.find(params[:id]) %>
  <h2>
    Collection <span class="title-h2"><%= collection.name %></span> of user <span class="title-h2"><%= user.username %></span>
  </h2>
  <p style="color: green"><%= notice %></p>
  <p style="color: red"><%= alert %></p>

  <div class="container-notes">
  <% collection_notes = find_collection_notes(collection.id) %>

    <% collection_notes.each do |collection_note| %>
      <% note = find_note(collection_note.note_id) %>
      <div class="note">
        <h3 class="note-title">
          <%= note.title %>
        </h3>
        <p class="note-text">
          <%= note.text %>
        </p>
        <div class="note-show-button">
          <%= button_to '<i class="fa-solid fa-eye"></i>'.html_safe, user_note_path(user.id, note), method: :get, class: "button-primary", style:"width:95%" %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
      