config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  resources :collection_notes
  resources :collections
  get 'logout' => 'session#destroy', :as => 'logout'
  get 'login' => 'session#new', :as => 'login'
  post 'login' => 'session#create'
  delete 'users/:user_id/notes/:id', to: 'notes#destroy', as: 'destroy_user_note'
  resources :users do
    resources :notes do
      get 'share' => 'notes#share', :as => 'share'
      post 'share_with_friend' => 'notes#share_with_friend'
      delete 'unshare_with_friend' => 'notes#unshare_with_friend'
    end
    resources :collections do
      post 'add_note' => 'collections#add_note'
      delete 'delete_note' => 'collections#delete_note'
    end
    resources :friendships, only: [:index, :create, :update, :destroy]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
  root "users#login"
end

app/models/note.rb
class Note < ApplicationRecord

    belongs_to :user

    has_many :note_permissions
    has_many :collections_notes

    validates :title, presence: true, length: {maximum: 11}
    validates :text, presence: true

    mount_uploader :image, ImageUploader
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :destroy, only: %i[destroy ]

  # GET /notes
  def index
    puts "-------------------------------GET NOTES----------------"
    @notes = Note.all
  end

  # GET /notes/1
  def show
    puts "-------------------------------GET NOTE----------------"
    @note = Note.find(params[:id])
  end

  # GET /notes/new
  def new
    puts "-------------------------------NEW NOTE----------------"
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
    puts "-------------------------------EDIT NOTE----------------"
    @note = Note.find(params[:id])
  end

  # POST /notes
  def create
    puts "-------------------------------CREATE NOTE----------------"
    @user = User.find(params[:user_id])
    @note = @user.notes.create(note_params)

    if @note.save
      np = NotePermission.create({user_id:@user.id, note_id: @note.id})
      redirect_to user_notes_url(@user)
    else
      render :new, status: :unprocessable_entity
    end
  end


  # PATCH/PUT /notes/1
  def update
    puts "-------------------------------UPDATE NOTE----------------"
    if logged?

      @note = Note.find(params[:id])
      
      if @note.update(note_params)
        redirect_to user_notes_url(@note.user_id)
      else
        render 'edit'
      end
    end
  end

  # DELETE /notes/1
  def destroy
    puts "-------------------------------DELETE NOTE----------------"
    if logged?
      note = Note.find(params["note_id"])
      CollectionNote.where(note_id: note).destroy_all
      note.destroy

      redirect_to user_notes_url(params["user_id"])
    end
  end

  def share
    @note = Note.find(params["note_id"])
    @note_permission = @note.note_permissions
  end

  def share_with_friend
    
    note = Note.find(params["note_id"])
    friend_to_share = User.find(params["friend_id"])
    np = NotePermission.create({user_id:friend_to_share.id, note_id: note.id})
    redirect_to user_note_share_path(params["user_id"], note)
  end

  def unshare_with_friend

    NotePermission.where(note_id: params["note_id"], user_id: params["friend_id"]).destroy_all
    
    redirect_to user_note_share_url(params["user_id"],params["note_id"])
  end
 # def unshare_with_friend

  #   note_permission = NotePermission.where(note_id: params["note_id"], user_id: params["friend_id"])
  #   note_permission.delete
  #   redirect_to user_note_share_url(params["user_id"],params["note_id"])
  # end

  private

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :text, :image)
    end
    def logged?
      session[:username]
    end
end

app/helpers/notes_helper.rb
module NotesHelper

  def find_notes(user_id)
    notes = []

    notes = Note.where(user_id: user_id.to_i)

    notes = notes.group_by(&:user_id)        
  end

  def find_shared_notes(user_id)
    Note.joins(:note_permissions)
    .where("note_permissions.user_id = ? AND notes.user_id != ?", user_id, user_id)
 
  end
  def find_note(note_id)

    Note.find(note_id)
      
  end

  def user_session_is_admin?
    if logged?
      admin = User.where(username: session[:username]).first.admin
    end
    admin
  end

  def count_notes_user(user_id)
    nnotes = Note.where(user_id: user_id).count
  end


  def have_permission(note_id, user_id)
    NotePermission.where(note_id: note_id, user_id: user_id)
  end


  def logged?
    session[:username]
  end
end

app/views/notes/edit.html.erb
<div>
  <h2 >Edit note: <span class="title-h2"><%= @note.title %></span></h2> 
</div>              
<!-- /Row with title -->
<div class="show-note-container">
  <div class="note-info-container">
    <%= form_with(scope: :note, model: [ :user, @note ], local: true) do |form| %>
    <% if @note.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2>
        <%= pluralize(@note.errors.count, "error") %> prohibited
        this note from being saved:
      </h2>
      <ul>
        <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <p>
      <h3><%= form.label :title %></h3><br>
      <%= form.text_field :title, style: 'padding: 5px; height: 25px; border-radius: 10px';%>
    </p>

    <p>
        <h3><%= form.label :text %></h3><br>
      <%= form.text_area :text, style: 'padding: 5px; height: 200px; border-radius: 10px;'%>
    </p>
    <p>
      <h3><%= form.label :image %></h3><br>
      <%= form.file_field :image %>
    </p>


    <br>
    <div>
      <%= form.submit class: "button-primary" %>
      <%= link_to 'Back', :back, class: "button-primary" %>
    </div>

    <% end %>
      
  </div>
  <div >
    <h3 >Add to a collection:</h3>
    <div id="collection">
     <%collections = find_collections(params[:user_id])%>
     <% collections.each do |collection| %>
      <div class="collection-card">
        <div class="collection-info">
          <h3>
            <i class="fa fa-book fa-xl"></i>
            <%= collection.name %>
          </h3>
        
        </div>
        <div>
          <%if !belong_to_collection(collection.id, @note.id).present? %>
            <%= button_to '<i class="fa fa-plus"></i>'.html_safe, user_collection_add_note_path({note_id: @note.id, user_id: params[:user_id], collection_id: collection.id}), method: :post, class: "button-primary" %> 
          <%else%>
           <%= button_to '<i class="fa-solid fa-xmark"></i>'.html_safe, user_collection_delete_note_path({note_id: @note.id, user_id: params[:user_id], collection_id: collection.id}), method: :delete, class: "button-primary" %> 
          <%end%>
        </div>
      </div>
  <% end %>
  </div>
  </div>

</div>

app/views/notes/index.html.erb
<% if !logged? %>
  <%= controller.redirect_to root_path %>
<% else %>
  <p style="color: green"><%= notice %></p>
  <% user = get_user_name(params[:user_id]) %>
  <div>
  <h2>Notes of <span class="title-h2"><%=user.username%></span></h2>
  <% if user_session_is_admin?%>
    <%= link_to 'Back to users', users_url, class: "button-primary" %>
  <% end %>
  <% notes = find_notes(params[:user_id]) %>
  <% shared_notes = find_shared_notes(params[:user_id]) %>
  <div class="container-notes">
  <%= button_to '<i class="fa fa-plus"></i>'.html_safe, new_user_note_url(params[:user_id]),method: :get,  class: "add-note" %>
  <% notes.each_pair do |user_id, user_notes| %>
    <% user_notes.each do |note| %>
      <div class="note">
        <h3 class="note-title">
          <%= note.title %>
        </h3>
        <p class="note-text">
          <%= note.text %>
        </p>
        <div class="note-show-button">
          <%= button_to '<i class="fa-solid fa-eye"></i>'.html_safe, user_note_path(user_id, note), method: :get, class: "button-primary", style:"width:95%" %>
        </div>
      </div>
      
    <% end %>
    </div>
  <% end %>
  </div>
  <% if shared_notes.present? %>
  <div style="padding-top: 25px">
  
  <h2>Shared notes</h2>
  <div class="container-notes">
    <% shared_notes.each do |note| %>
      <div class="note">
        <h3 class="note-title">
          <%= note.title %>
        </h3>
        <p class="note-text">
          <%= note.text %>
        </p>
        <div class="note-show-button">
          <%= button_to '<i class="fa-solid fa-eye"></i>'.html_safe, user_note_path(user.id, note), method: :get, class: "button-primary", style:"width:95%" %>
        </div>
      </div>
      
    <% end %>
    </div>
  </div>
  <% end %>
<% end %>

app/views/notes/new.html.erb
<% if !logged? %>
<%= controller.redirect_to root_path %>
<% else %>
<div >
  <!-- Row with title -->
  <div>
        <h2 >New note</h2>               
  </div>
  <!-- /Row with title -->
  <% if @note.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2>
      <%= pluralize(@note.errors.count, "error") %> prohibited
      this note from being saved:
    </h2>
    <ul>
      <% @note.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div>
    <%= form_with scope: :note, model: [ :user, @note ], local: true do |form| %>
    <p>
      <h3><%= form.label :title %></h3><br>
      <%= form.text_field :title%>
    </p>

    <p>
       <h3><%= form.label :text %></h3><br>
      <%= form.text_area :text, style: 'padding: 5px; height: 200px; border-radius: 10px;'%>
    </p>

    <p>
      <h3><%= form.label :image %></h3><br>
      <%= form.file_field :image %>
    </p>
    <br>
    <div>
      <%= form.submit class: "button-primary" %>
      <%= link_to 'Back', :back, class: "button-primary" %>
    </div>

    <% end %>

  </div>
</div>
<% end %>

app/views/notes/share.html.erb
<div>
  <h2 >Sharing Mangment of note: <span class="title-h2"><%= @note.title %></span></h2> 
</div>
<% user = get_user_name(params[:user_id]) %>

<h3>Friends that have access: </h3>
<div class="friends-container">
  <% friendships = get_all_friendships(user.id) %>
  <% friendships.each do |friendship| %>
    <%friend = find_user(user.id, friendship)%>
    <% if have_permission(@note.id, friend.id).present?%>
    <div class="friend">
      <div class="friend-title">
        <i class="fa-solid fa-user fa-2xl"></i> <%=friend.username%>
      </div>
      <div class="friend-bottons">
        <%= button_to '<i class="fa-solid fa-xmark"></i>'.html_safe, user_note_unshare_with_friend_path({note_id: @note.id, user_id: user.id, friend_id: friend.id}), :method => :delete,  class: "button-primary"%>
      </div>
    </div>
  <% end %>
  <% end %>
  
</div>

<h3>Share note: </h3>
<div class="friends-container">
  <% friendships = get_all_friendships(user.id) %>
  <% friendships.each do |friendship| %>
    <%friend = find_user(user.id, friendship)%>
    <% if !have_permission(@note.id, friend.id).present?%>
    <div class="friend">
      <div class="friend-title">
        <i class="fa-solid fa-user fa-2xl"></i> <%=friend.username%>
      </div>
      <div class="friend-bottons">
        <%= button_to '<i class="fa fa-share"></i>'.html_safe, user_note_share_with_friend_path({note_id: @note.id, user_id: user.id, friend_id: friend.id}), :method => :post,  class: "button-primary"%>
      </div>
    </div>
  <% end %>
  <% end %>
  
</div>
<%= button_to '<i class="fa-solid fa-rotate-left"></i> Back'.html_safe , user_note_path(params[:user_id], @note.id), :method => :get, class: "button-primary" %>

app/views/notes/show.html.erb
<h2>
  Information about: <span class="title-h2"><%= @note.title %></span>
</h2>
<% user = get_user_name(params[:user_id]) %>
<div class="show-note-container">
  <div class="note-info-container">

    <p class="note-info-text">
      <%= @note.text %>
    </p>
    
     <div class="notes-options">
      <% if user.id ==  @note.user_id%>
        <%= button_to '<i class="fa fa-trash"></i>'.html_safe, destroy_user_note_path({note_id: @note.id, user_id: user.id}), method: :delete, class: "button-primary" %>
        <%= button_to '<i class="fa fa-gear"></i>'.html_safe, edit_user_note_path(params[:user_id], @note), method: :get, class: "button-primary" %>
        <%= button_to '<i class="fa fa-share"></i>'.html_safe, user_note_share_path(params[:user_id], @note), method: :get,  class: "button-primary"%>
      <% end %>
        <%= link_to '<i class="fa-solid fa-rotate-left"></i>'.html_safe , :back, class: "button-primary" %>
    </div>
  </div>
  <div>
    <h3>
        Image:
    </h3>
  <% if @note.image? %>
     <%= image_tag(@note.image.url, alt: 'Image', class: 'note-info-image') if @note.image? %>
    <% else%>
      Not image attached
    <% end %> 
  </div>
</div>