config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  resources :collection_notes
  resources :collections
  get 'logout' => 'session#destroy', :as => 'logout'
  get 'login' => 'session#new', :as => 'login'
  post 'login' => 'session#create'
  delete 'users/:user_id/notes/:id', to: 'notes#destroy', as: 'destroy_user_note'
  resources :users do
    resources :notes do
      get 'share' => 'notes#share', :as => 'share'
      post 'share_with_friend' => 'notes#share_with_friend'
      delete 'unshare_with_friend' => 'notes#unshare_with_friend'
    end
    resources :collections do
      post 'add_note' => 'collections#add_note'
      delete 'delete_note' => 'collections#delete_note'
    end
    resources :friendships, only: [:index, :create, :update, :destroy]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
  root "users#login"
end

app/models/user.rb
class User < ApplicationRecord
    before_create :set_default_admin
    has_many :notes, dependent: :destroy
    has_many :friendships, dependent: :destroy
    # has_many :friends, :through => :friendships
    has_many :note_permission
    has_many :collections, dependent: :destroy
    
    validates :username, presence: true, length: { maximum: 10 }, uniqueness: { case_sensitive: false }
    before_save { self.email = email.downcase }
    validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+[a-z]+\z/i }, uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, length: { minimum: 8 }

    private

    def set_default_admin
        self.admin ||= false
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: %i[ show edit update destroy ]
  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: "User was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1
  def update
    if logged?
      @user = User.find(params[:id])

      if @user.update(user_params)
        redirect_to users_path
      else
        render 'edit'
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: "User was successfully destroyed."
  end

  private
    # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username, :email, :password, :admin)
  end
  def set_default_admin
    self.admin ||= false
  end
  
  def logged?
    session[:username]
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_session_is_admin?
    if logged?
      admin = User.where(username: session[:username]).first.admin
    end
    admin
  end

  def get_user_name(user_id)
      user = User.where(id: user_id).first
  end

  def get_user_id(username)
    user = User.find_by(username: username).id
  end
  def logged?
    session[:username]
  end

end
  

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>

  <div>
   <%= form.label :username %><br>
    <%= form.text_field :username%>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.submit class: "button-primary" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="user">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>
  <p>
    <strong>Admin:</strong>
    <%= user.admin %>
  </p>

</div>

app/views/users/edit.html.erb
<% user = User.find(params[:id]) %>

<h2>Editing <span class="title-h2"><%=user.username%></span> profile</h2>

<%= form_with scope: :user, model: user, local: true do |form| %>

  <div>
    <%= form.label :username %><br>
    <%= form.text_field :username%>
  </div>

  <div>
    <%= form.label :email, style: "display: block; padding-top:10px" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label "New password", style: "display: block; padding-top:10px" %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.label "Confirm new password", style: "display: block; padding-top:10px" %>
    <%= form.password_field :password_confirmation %>
  </div>
  <% if user_session_is_admin? %>
    <div>
    <%= form.label "Administrator" ,style: "display: block; padding-top:10px"%>
    <%= form.check_box :admin, checked: user.admin %>
    </div>
  <% end %>
  <div>
    <%= form.submit class: "button-primary" %>
  </div>
<% end %>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users Managment</h1>

<div id="users">
  <% @users.each do |user| %>
    <div class="user-card">
      <div class="user-info">
      <h2>
      <% if user.admin %>
        <i class="fa-solid fa-user-shield fa-xl"></i>
      <% else %>
        <i class="fa-solid fa-user fa-2xl"></i>
      <% end %>
      </h2>
      <h2 style="padding-left: 20px">
        <%= user.username %> 
      </h2>
      
      </div>
      <div class="user-bottons">
        <%= button_to '<i class="fa-solid fa-user-pen"></i>'.html_safe, user_path(user.id), method: :get, class: "button-primary" %>
        <%= button_to '<i class="fa fa-sticky-note"></i>'.html_safe, user_notes_url(user.id), method: :get,  class: "button-primary"%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/login.html.erb
<body id="welcome">
  <header>
    <div class="center">
      <h1>Log in</h1>
    </div>
  </header>

    <div>
      <%= form_with class: 'col-xs-6', url: 'login', local: true do |form| %>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

        <p>
          <%= form.label :username %><br>
          <%= form.text_field :username, class: 'col-xs-12' %>
        </p>

        <p>
          <%= form.label :password %><br>
          <%= form.password_field :password_digest, class: 'col-xs-12' %>
        </p>

        <p>
          <%= form.submit 'Sign in' , class: "button-primary"%>
          <%= link_to 'Sign up', new_user_path, class: "button-primary"%>
        </p>
        <div>
        <p>
          <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
          <% end %>
        </p>
        </div>
      <% end %>

    </div>
</body>

app/views/users/new.html.erb
<body id="welcome">
  <header>
    <div class="center">
      <h1>Sign Up</h1>
    </div>
  </header>

  <div class="row center">
    <%= form_with scope: :user, class: 'col-xs-6', url: users_path, local: true do |form| %>  
      <p>
        <%= form.label :username %><br>
        <%= form.text_field :username, class: 'col-xs-12' %>
      </p>

      <p>
        <%= form.label :email %><br>
        <%= form.text_field :email, class: 'col-xs-12' %>
      </p>

      <p>
        <%= form.label :password %><br>
        <%= form.password_field :password, class: 'col-xs-12' %>
      </p>

      <p>
        <%= form.label :password_confirmation %><br>
        <%= form.password_field :password_confirmation, class: 'col-xs-12' %>
      </p>
      <p>
        <%= form.submit 'Sign up' , class: "button-primary"%>
        <%= link_to 'Back', root_path, class: "button-primary" %>
      </p>

    <% end %>
    <% if @user.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  </div>

</body>

app/views/users/show.html.erb
<% if !logged? %>
  <%= controller.redirect_to root_path %>
<% else %>
  <div>
    <% user = User.find(params[:id]) %>


  <h2>Profile of: <span class="title-h2"><%=user.username%></span> </h2>
    <%= form_with scope: :user, model: user, local: true do |form| %>
      <p style=>
        <h2>
          <% if user.admin %>
            <i class="fa-solid fa-user-shield fa-xl"></i>
          <% else %>
            <i class="fa-solid fa-user fa-2xl"></i>
          <% end %>
        </h2>
      </p>
      <p>
        <h3>
          Username: <%= user.username%>
        </h3>
      </p>
      <p>
        <h3>
          Email: <%= user.email%>
        </h3>
      </p>
      <p>
      <h3>
        <%= form.label "Number of notes: ", style:"padding-top: 15px" %>
        <%= count_notes_user(params[:id]) %>
      </h3>
      </p>
    <% end %>
    <br>
    <p>
      <%= link_to 'Edit profile', edit_user_path(user), class: "button-primary"%>
    </p>
  </div>
<% end %>