config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  resources :collection_notes
  resources :collections
  get 'logout' => 'session#destroy', :as => 'logout'
  get 'login' => 'session#new', :as => 'login'
  post 'login' => 'session#create'
  delete 'users/:user_id/notes/:id', to: 'notes#destroy', as: 'destroy_user_note'
  resources :users do
    resources :notes do
      get 'share' => 'notes#share', :as => 'share'
      post 'share_with_friend' => 'notes#share_with_friend'
      delete 'unshare_with_friend' => 'notes#unshare_with_friend'
    end
    resources :collections do
      post 'add_note' => 'collections#add_note'
      delete 'delete_note' => 'collections#delete_note'
    end
    resources :friendships, only: [:index, :create, :update, :destroy]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
  root "users#login"
end

app/helpers/layouts_helper.rb
module LayoutsHelper
	def user_id(username)
		User.where(username: username).first.id
	end

	def user_name(user_id)
		User.where(id: user_id).first
	end
end

app/views/layouts/_sidebar.erb
<% user_id = user_id(session[:username])%>
<div class="left_col scroll-view" style="width: 100%">
	
  <!-- menu profile quick info -->
  <div class="profile clearfix" style="padding: 10px">
    <h3 class="profile_info">
      <p>Welcome, <%= session[:username] %></p>
    </h3>
  </div>

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu ">
    <div class="menu_section">
      <ul class="nav side-menu" id="nav-menu">
        <!-- Edit view -->
        <li><%= link_to '<i class="fa fa-user"></i> Profile'.html_safe, user_path(user_id)  %></li>
        <!-- /Edit view -->  
      	<% if user_session_is_admin? %>
	        <!-- User admin view -->
          <li ><%= link_to '<i class="fa fa-id-card-o"></i> Admin management'.html_safe, users_path %></li>
	        <!-- /User admin view --> 
	      <% end %>
        <li ><%= link_to '<i class="fa fa-sticky-note"></i> Notes list'.html_safe, user_notes_url(user_id) %></li>
        <!-- Collections view -->
        <li><%= link_to '<i class="fa fa-book"></i> Collections list'.html_safe,user_collections_url(user_id) %></li>
        <!-- /Collections view -->
        <!-- Friends view -->
        <li><%= link_to '<i class="fa fa-address-book"></i> Friends list'.html_safe, user_friendships_url(user_id) %></li>
        <!-- /Friends view -->  
      </ul>
    </div>
    <div style="text-align: center">
      <%= link_to 'Log Out', '/logout', class: "button-primary"  %>
    </div>
  </div>
  <!-- /sidebar menu -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <title>Note App</title>
    
    <!--Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/e071f39ef9.js" crossorigin="anonymous"></script>
    <!--CSS-->
    <%= stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "note", media: 'all', 'data-turbolinks-track': 'reload'  %>
    <%= stylesheet_link_tag "user", media: 'all', 'data-turbolinks-track': 'reload'   %>
    <%= stylesheet_link_tag "collection", media: 'all', 'data-turbolinks-track': 'reload'   %>
    <%= stylesheet_link_tag "friendship", media: 'all', 'data-turbolinks-track': 'reload'   %>
    <%= stylesheet_link_tag "sidebar", media: 'all', 'data-turbolinks-track': 'reload'   %>
    <!-- Bootstrap CSS -->
    <%# <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%# <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> %>
    <%# <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%# <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css" %> 
    
    <!-- Javascript-->
    
    <%# <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> %>
    
  </head>
  <body class="welcome">
    <% if !logged? %>
      <div id="welcome-container">
        <%= yield %>
      </div>
    <% else %>
      <div id="wrapper">
        <div class="col-md-3 left_col">
          <%= render 'layouts/sidebar' %>
        </div>
        <div id="content">
          <%= yield %>
        </div>
      </div>
    <% end %>
  </body>
</html>